# Generated by Django 5.0.3 on 2024-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_product_total_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_prize',
            field=models.FloatField(default=0),
        ),
    ]
