# Generated by Django 5.0.3 on 2024-12-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schedule_time',
            field=models.CharField(max_length=100),
        ),
    ]
