# Generated by Django 5.0.3 on 2025-01-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_item',
        ),
    ]
